name: "Publish articles to Qiita"
description: "Publish articles to Qiita using qiita-cli"
author: "Qiita Inc."

inputs:
  root:
    required: false
    default: '.'
    description: "Root directory path"
  qiita-token:
    required: true
    description: "Qiita API token"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18.16.0"
    - name: Install qiita-cli
      run: npm install -g @qiita/qiita-cli@v1.0.0
      shell: bash
    - name: Publish articles
      run: qiita publish --all --root ${{ inputs.root }}
      env:
        QIITA_TOKEN: ${{ inputs.qiita-token }}
      shell: bash
    - name: Commit and push diff # Not executed recursively even if `push` is triggered. See https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
      run: |
        git add ${{ inputs.root }}/public/*
        if ! git diff --staged --exit-code --quiet; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'Updated by qiita-cli'
          git push
        fi
      shell: bash
